name: NightChatRestricter
version: ${version}
main: zxc.mrdrag0nxyt.nightChatRestricter.NightChatRestricter
api-version: '1.18'
authors: [ MrDrag0nXYT (drakoshaslv) ]
website: https://drakoshaslv.ru

commands:
  reloadnightchatrestricter:
    aliases:
      - reloadncr
    permission: ncr.command

permissions:
  ncr.bypass.chat:
    default: op
  ncr.bypass.command:
    default: op

  ncr.bypass:
    default: op
    children:
      ncr.bypass.chat: true
      ncr.bypass.command: true

  ncr.reload:
    default: op

  ncr.*:
    default: op
    children:
      ncr.bypass: true
      ncr.reload: true
